-- MySQL Script generated by MySQL Workbench
-- Sat Nov 11 17:29:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema by_me
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `by_me` ;

-- -----------------------------------------------------
-- Schema by_me
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `by_me` DEFAULT CHARACTER SET utf8 ;
USE `by_me` ;

-- -----------------------------------------------------
-- Table `by_me`.`materiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by_me`.`materiais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `custo` DOUBLE NOT NULL,
  `observacao` VARCHAR(200) NULL,
  `data_cadastro` DATETIME NOT NULL,
  `peso` DOUBLE NOT NULL,
  `versao` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by_me`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by_me`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `versao` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `rendimento` INT NOT NULL,
  `valor_venda` DOUBLE NOT NULL,
  `modo_preparo` VARCHAR(1000) NULL,
  `data_cadastro` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by_me`.`produtos_materiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by_me`.`produtos_materiais` (
  `quantidade_material` DOUBLE NOT NULL,
  `material_versao` INT NOT NULL,
  `material_codigo` INT NOT NULL,
  `produto_codigo` INT NOT NULL,
  `produto_versao` INT NOT NULL,
  `produtos_id` INT NULL,
  `materiais_id` INT NULL,
  INDEX `fk_produtos_materiais_materiais1_idx` (`materiais_id` ASC),
  CONSTRAINT `fk_produtos_materiais_produtos`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `by_me`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_materiais_materiais1`
    FOREIGN KEY (`materiais_id`)
    REFERENCES `by_me`.`materiais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by_me`.`produtos_materiais_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by_me`.`produtos_materiais_historico` (
  `quantidade_material` DOUBLE NOT NULL,
  `material_versao` INT NOT NULL,
  `material_codigo` INT NOT NULL,
  `produto_versao` INT NOT NULL,
  `produto_codigo` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `by_me`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `by_me`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
